version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: orange_db
    environment:
      POSTGRES_DB: orange_db
      POSTGRES_USER: orange
      POSTGRES_PASSWORD: 4321
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@pgadmin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "5050:80"
    depends_on:
      - postgres
